import QtQuick
import QtQuick.Window
import QtTest
import Quickshell
import qs.Commons
import "Native" as Native
import "Native/Theme.js" as Theme
import "Native/Model.js" as Model

ShellRoot {
    id: root
    property int index: 0
    property var overflowCards: []
    property Native.Service service: Native.Service { autostart: false }
    property TestCase driver: TestCase { name: "NativeInteractions"; when: false }
    property QtObject controller: QtObject {
        property var service: root.service
        property string page: "translate"
        property bool opened: true
        readonly property string language: root.service.language
        function tr(key) { return root.service.tr(key) }
        function dismiss() {
            opened = false
        }
        function handleEscape() { if (root.service.busy) root.service.stop(); dismiss() }
        function capture(action) { root.service.capture(action) }
    }
    property QtObject shellApi: QtObject {
        function summon(id, payload) {
            root.controller.opened = true
            root.controller.page = "translate"
        }
    }
    property Window window: Window {
        width: 660; height: 850; visible: true; color: Color.background
        Native.PanelContent {
            id: panel
            x: 40; y: 40; width: 440; height: 600
            controller: root.controller; visible: root.controller.opened
        }
    }
    function check(condition, message) { if (!condition) throw new Error(message) }
    function waitFor(predicate, message, timeout) {
        for (var i = 0; i < Math.ceil((timeout || 2000)/20) && !predicate(); i++) driver.wait(20)
        check(predicate(), message)
    }
    function find(name, item) {
        item = item || panel
        if (item.objectName === name) return item
        for (var i = 0; i < item.children.length; i++) { var value = find(name,item.children[i]); if (value) return value }
        return null
    }
    function item(name) { var value = find(name); check(!!value,"Missing " + name); return value }
    function reveal(value) {
        for (var parent = value.parent; parent; parent = parent.parent) {
            if (typeof parent.contentY === "number" && parent.contentHeight > parent.height) {
                var position = value.mapToItem(parent,0,0)
                parent.contentY = Math.max(0,Math.min(parent.contentHeight-parent.height,parent.contentY+position.y-parent.height/2))
            }
        }
        driver.wait(20)
    }
    function click(name) { var value = item(name); reveal(value); driver.mouseClick(value,value.width/2,value.height/2,Qt.LeftButton,Qt.NoModifier,0); driver.wait(20) }
    function edit(name, text) {
        var value = item(name); reveal(value); driver.mouseClick(value,10,value.height/2,Qt.LeftButton,Qt.NoModifier,0)
        driver.keyClick(Qt.Key_A,Qt.ControlModifier,0); driver.keyClick(Qt.Key_Backspace,Qt.NoModifier,0)
        for (var i = 0; i < text.length; i++) driver.keyClick(text.charAt(i),Qt.NoModifier,0)
        driver.wait(20)
    }
    function choose(name, value) {
        var dropdown = item(name)
        click(name); check(dropdown.popupOpen,"Dropdown did not open: " + name)
        var current = dropdown.options.findIndex(function(option) { return option.value === dropdown.value })
        var target = dropdown.options.findIndex(function(option) { return option.value === value })
        check(target >= 0,"Missing dropdown option")
        var key = target > current ? Qt.Key_Down : Qt.Key_Up
        for (var i = 0; i < Math.abs(target-current); i++) driver.keyClick(key,Qt.NoModifier,0)
        driver.keyClick(Qt.Key_Return,Qt.NoModifier,0); driver.wait(30)
    }
    function rpc(method, params) {
        var completed = false; var success = false; var result
        service.request(method,params || {},function(ok,data) { completed = true; success = ok; result = data })
        waitFor(function() { return completed },"RPC did not complete: " + method)
        check(success,"RPC failed: " + method); return result
    }
    function page(value) { controller.opened = true; click("tab." + value); check(controller.page === value,"Tab failed"); driver.wait(30) }
    function dragService(provider,to) {
        var list=item("serviceList"), handle=item("service.drag."+provider)
        reveal(handle)
        var start=handle.mapToItem(list,handle.width/2,handle.height/2), target=(to+0.5)*list.stride
        driver.mousePress(handle,handle.width/2,handle.height/2,Qt.LeftButton,Qt.NoModifier,0)
        for (var i=1;i<=12;i++) driver.mouseMove(list,start.x,start.y+(target-start.y)*i/12,12)
        driver.mouseRelease(list,start.x,target,Qt.LeftButton,Qt.NoModifier,0)
        driver.wait(130)
    }
    function query(text) {
        page("translate"); edit("translationInput",text); click("translateSubmit")
        waitFor(function() { return !service.busy && service.cards.length === 2 },"Translation did not finish")
    }
    property var cases: [
        {name:"backend-ready-and-settings",run:function() { check(service.ready,"Backend not ready"); check(service.settings.preferences.language === "en","Settings missing") }},
        {name:"system-sans-serif-throughout-native-ui",run:function() {
            var count=0
            function inspect(value) {
                if (typeof value.text === "string" && value.font) {
                    check(value.font.family==="sans-serif","Unexpected font in "+value.objectName+": "+value.font.family)
                    count++
                }
                for (var i=0;i<value.children.length;i++) inspect(value.children[i])
            }
            ["translate","settings","history","favorites"].forEach(function(name) { page(name); inspect(panel) })
            check(count>30,"Typography coverage missing")
            page("translate")
            check(item("sourceLanguage").fontFamily==="sans-serif","Dropdown menu font was not changed")
        }},
        {name:"mouse-submit-and-result-cards",run:function() { query("hello"); check(service.cards.every(function(card) { return !card.pending }),"Pending card"); check(item("resultText.Bing").readOnly,"Result editable") }},
        {name:"overflow-hint-appears-and-click-scrolls",run:function() { overflowCards=service.cards; service.cards=[{service:"Bing",text:"hello",paragraphs:Array(60).fill("translation line"),detected_from:"en",detected_to:"zh-Hans"}]; driver.wait(40); var scroll=item("resultsScroll"); scroll.contentY=0; check(item("resultsOverflowHint").visible && item("scrollMoreResults").tooltipText===service.tr("moreResults"),"No cue for hidden translations"); click("scrollMoreResults"); check(scroll.contentY>0,"Down arrow did not scroll") }},
        {name:"overflow-hint-hides-at-bottom-and-returns-above",run:function() { var scroll=item("resultsScroll"); scroll.contentY=scroll.contentHeight-scroll.height; driver.wait(20); check(!item("resultsOverflowHint").visible,"Cue remains at bottom"); scroll.contentY=0; driver.wait(20); check(item("resultsOverflowHint").visible,"Cue did not return on scrolling up") }},
        {name:"overflow-hint-hidden-for-empty-or-fitting-results",run:function() { service.cards=[]; driver.wait(30); check(!item("resultsOverflowHint").visible,"Empty results show a cue"); service.cards=[{service:"Bing",text:"hello",paragraphs:["short translation"]}]; item("resultsScroll").contentY=0; driver.wait(30); check(!item("resultsOverflowHint").visible,"Fitting results show a cue"); service.cards=overflowCards; driver.wait(30); item("resultsScroll").contentY=0 }},
        {name:"enter-submits",run:function() { edit("translationInput","keyboard"); driver.keyClick(Qt.Key_Return,Qt.NoModifier,0); waitFor(function() { return !service.busy && service.cards[0].text === "keyboard" },"Enter did not submit") }},
        {name:"focus-and-enter-without-mouse-click",run:function() { service.clear(); panel.focusInput(); ["f","o","c","u","s"].forEach(function(key) { driver.keyClick(key,Qt.NoModifier,0) }); check(item("translationInput").activeFocus && service.text==="focus","Input did not receive keyboard focus"); driver.keyClick(Qt.Key_Return,Qt.NoModifier,0); waitFor(function() { return !service.busy && service.cards.length && service.cards[0].text==="focus" },"Focused Enter did not submit") }},
        {name:"keypad-enter-submits",run:function() { edit("translationInput","keypad"); driver.keyClick(Qt.Key_Enter,Qt.NoModifier,0); waitFor(function() { return !service.busy && service.cards.length && service.cards[0].text==="keypad" },"Keypad Enter did not submit") }},
        {name:"empty-input-submit-disabled",run:function() { edit("translationInput","   "); check(!item("translateSubmit").enabled,"Blank query can submit") }},
        {name:"clear-and-submit-icons-keyboard-and-layout",run:function() { var clear=item("clearInput"), submit=item("translateSubmit"), target=item("targetLanguage"); check(clear.text==="" && clear.name==="clear" && clear.tooltipText===service.tr("clear"),"Clear icon missing name or tooltip"); check(submit.text==="" && submit.name==="send" && submit.tooltipText===service.tr("translate"),"Translate icon missing name or tooltip"); check(clear.parent===submit.parent && clear.parent.parent===target.parent.parent,"Actions do not share the control strip"); check(target.width>0 && submit.x+submit.width<=submit.parent.width+1,"Actions overflow the narrow panel"); clear.forceActiveFocus(); driver.keyClick(Qt.Key_Space,Qt.NoModifier,0); check(service.text==="" && item("translationInput").activeFocus,"Keyboard Clear failed"); edit("translationInput","icon keyboard"); submit.forceActiveFocus(); driver.keyClick(Qt.Key_Return,Qt.NoModifier,0); waitFor(function() { return !service.busy && service.cards.length && service.cards[0].text==="icon keyboard" },"Keyboard Translate failed") }},
        {name:"language-group-centered-with-independent-actions",run:function() { var previous=panel.width; [440,480,580].forEach(function(width) { panel.width=width; driver.wait(30); var input=item("translationInput"), source=item("sourceLanguage"), target=item("targetLanguage"), actions=item("translationActions"); var left=source.mapToItem(panel,0,0).x, right=target.mapToItem(panel,target.width,0).x, inputCenter=input.mapToItem(panel,input.width/2,0).x; check(Math.abs((left+right)/2-inputCenter)<1,"Language group not centered at width "+width); check(Math.abs(source.width-target.width)<=1,"Language boxes have different widths: "+source.width+" / "+target.width); check(right+Style.spacing.xs<=actions.mapToItem(panel,0,0).x+1,"Actions overlap language boxes"); }); panel.width=previous; driver.wait(30) }},
        {name:"pending-loading-icon-animates-and-stops",run:function() { service.translate("hang fixture"); waitFor(function() { return !!find("loading.Bing") && item("loading.Bing").visible },"Pending loading icon missing"); var spinner=item("loading.Bing"); check(spinner.running && spinner.label===service.tr("loading"),"Loading icon has no animation or accessible label"); var angle=spinner.rotation; driver.wait(120); check(Math.abs(spinner.rotation-angle)>5,"Loading icon is static"); service.stop(); driver.wait(30); spinner=item("loading.Bing"); check(!spinner.visible && !spinner.running,"Cancelled request left loading icon running"); query("hello"); check(!item("loading.Bing").visible && !item("loading.Bing").running,"Completed result left loading icon running") }},
        {name:"busy-submit-icon-cancels-and-restores-send",run:function() { edit("translationInput","slow fixture"); click("translateSubmit"); var submit=item("translateSubmit"); check(service.busy && submit.name==="stop" && submit.tooltipText===service.tr("cancel") && submit.enabled,"Busy action is not Stop"); click("translateSubmit"); check(!service.busy && submit.name==="send" && service.text==="slow fixture" && item("translationInput").activeFocus,"Stop lost input or focus"); driver.wait(200); check(service.cards.every(function(card) { return !card.pending }),"Cancelled request restored pending cards") }},
        {name:"dictionary-repeat-suppressed-with-copy-preserved",run:function() { var card={dict:{meanings:[["int.","hello"],["n.","greeting"]]},paragraphs:["int. hello\nn. greeting"]}; check(Model.repeatsDictionary(card),"Duplicate dictionary block remains"); check(Model.translated(card)==="int. hello\nn. greeting","Copy text changed"); card.paragraphs=["a different translation"]; check(!Model.repeatsDictionary(card),"Distinct translation was hidden") }},
        {name:"shift-enter-newline",run:function() { edit("translationInput","line"); var count=rpc("tests.state").counts.translate; item("translationInput").forceActiveFocus(); driver.keyClick(Qt.Key_Return,Qt.ShiftModifier,0); check(service.text === "line\n","Newline missing"); check(rpc("tests.state").counts.translate === count,"Shift+Enter submitted") }},
        {name:"clear-input-and-results",run:function() { click("clearInput"); check(service.text === "" && service.cards.length === 0,"Clear failed") }},
        {name:"dropdown-keyboard-selection",run:function() { choose("sourceLanguage","en"); choose("targetLanguage","ja"); check(service.from === "en" && service.to === "ja","Languages not changed") }},
        {name:"dropdown-escape-does-not-close-panel",run:function() { click("sourceLanguage"); driver.keyClick(Qt.Key_Escape,Qt.NoModifier,0); check(!item("sourceLanguage").popupOpen && controller.opened,"Escape closed panel with dropdown") }},
        {name:"swap-languages",run:function() { click("swapLanguages"); check(service.from === "ja" && service.to === "en","Swap failed"); check(item("translationInput").activeFocus,"Swap retained button focus") }},
        {name:"language-selection-restores-input-focus",run:function() { choose("sourceLanguage","en"); check(item("translationInput").activeFocus,"Language picker retained input focus"); edit("translationInput","after picker"); driver.keyClick(Qt.Key_Return,Qt.NoModifier,0); waitFor(function() { return !service.busy && service.cards.length && service.cards[0].text==="after picker" },"Enter after language selection failed") }},
        {name:"clear-restores-input-focus",run:function() { click("clearInput"); check(item("translationInput").activeFocus,"Clear retained button focus") }},
        {name:"provider-error-and-individual-retry",run:function() { query("failure fixture"); var retained=service.cards.find(function(card) { return card.service === "YoudaoDict" }).paragraphs[0]; click("retry.Bing"); waitFor(function() { return !service.busy && !service.cards.find(function(card) { return card.service === "Bing" }).error },"Retry failed"); check(service.cards.find(function(card) { return card.service === "YoudaoDict" }).paragraphs[0] === retained,"Retry lost another result") }},
        {name:"copy-result-through-private-ipc",run:function() { var button=item("copy.Bing"); check(button.text==="" && button.name==="copy" && button.tooltipText===service.tr("copy"),"Copy is not an accessible icon"); click("copy.Bing"); check(rpc("tests.state").last.copy.text === "translated: failure fixture","Wrong copied result") }},
        {name:"favorite-toggle-and-state",run:function() { var button=item("favorite.Bing"); check(button.text==="" && button.name==="favorites" && button.tooltipText===service.tr("favorite"),"Favorite is not an accessible icon"); click("favorite.Bing"); check(button.filled && rpc("tests.state").favorites.length===1,"Favorite state missing"); click("favorite.Bing"); check(!button.filled && rpc("tests.state").favorites.length===0,"Favorite not removed"); click("favorite.Bing"); click("favorite.Bing") }},
        {name:"favorite-removal-rejects-stale-status",run:function() { var card=service.cards.find(function(card) { return card.service==="Bing" }), key=service.favoriteKey(card); service.favorite(card); waitFor(function() { return !!service.favoriteStates[key] },"Favorite not saved"); rpc("tests.mode",{mode:"slow_status"}); service.syncFavorite(card); rpc("tests.state"); var removed=false; service.removeFavorite(service.favoriteStates[key],function(ok) { removed=ok }); waitFor(function() { return removed },"Favorite not removed"); driver.wait(250); check(!service.favoriteStates[key] && rpc("tests.state").favorites.length===0,"Late status restored removed favorite"); rpc("tests.mode",{mode:""}) }},
        {name:"icon-actions-work-with-keyboard",run:function() { var before=rpc("tests.state").counts.copy; item("copy.Bing").forceActiveFocus(); driver.keyClick(Qt.Key_Space,Qt.NoModifier,0); check(rpc("tests.state").counts.copy===before+1,"Copy icon does not respond to Space"); item("favorite.Bing").forceActiveFocus(); driver.keyClick(Qt.Key_Return,Qt.NoModifier,0); check(rpc("tests.state").favorites.length===1,"Favorite icon keyboard activation failed") }},
        {name:"history-tab-load",run:function() { page("history"); waitFor(function() { return item("recordsView").rows.length === 50 },"History missing"); var id=item("recordsView").rows[0].id; check(item("record.copy."+id).text==="" && item("record.favorite."+id).text==="","History action labels remain") }},
        {name:"history-pagination",run:function() { click("loadMore"); waitFor(function() { return item("recordsView").rows.length > 50 && !item("recordsView").loading },"Pagination failed") }},
        {name:"history-full-results-expand-and-favorite-state",run:function() { var record=item("recordsView").rows[0]; click("record.expand."+record.id); check(record.details.length===2 && record.details.every(function(card) { return !!find("result."+card.service,item("recordsView")) }),"Stored provider results not expanded"); waitFor(function() { return Object.keys(service.pending).length===0 },"History state not synchronized"); var button=item("record.favorite."+record.id), saved=button.filled; click(button.objectName); waitFor(function() { return button.filled!==saved },"History favorite state did not toggle"); click(button.objectName); waitFor(function() { return button.filled===saved },"History favorite state did not restore"); click("record.expand."+record.id); check(!find("result."+record.details[0].service,item("recordsView")),"Full results did not collapse") }},
        {name:"history-search-and-clear-search",run:function() { edit("recordsSearch","record 60"); waitFor(function() { return item("recordsView").rows.length===1 },"Search did not filter"); check(item("recordsView").rows[0].text==="record 60","Wrong search result"); edit("recordsSearch",""); waitFor(function() { return item("recordsView").rows.length===50 },"Clearing search did not restore history") }},
        {name:"history-retranslate",run:function() { var record=item("recordsView").rows[0]; click("record.translate."+record.id); waitFor(function() { return controller.page === "translate" && !service.busy },"Retranslate failed"); check(service.text === record.text,"Wrong history text") }},
        {name:"favorite-tab-and-remove",run:function() { page("favorites"); waitFor(function() { return item("recordsView").rows.length === 1 },"Favorites missing"); var button=item("record.favorite."+item("recordsView").rows[0].id); check(button.filled && button.text==="" && button.tooltipText===service.tr("remove"),"Saved favorite icon is not distinct"); click(button.objectName); waitFor(function() { return item("recordsView").rows.length === 0 },"Favorite removal failed") }},
        {name:"history-clear-two-step-confirmation",run:function() { page("history"); waitFor(function() { return item("recordsView").rows.length > 0 },"History missing"); var before=rpc("tests.state").history_count; click("clearHistory"); check(item("recordsView").confirmClear,"No confirmation"); check(rpc("tests.state").history_count === before,"Deleted before confirmation"); click("clearHistory"); waitFor(function() { return item("recordsView").rows.length === 0 },"History clear failed") }},
        {name:"settings-tab-and-service-toggle",run:function() { page("settings"); var before=service.settings.services.bing; click("service.bing"); waitFor(function() { return service.settings.services.bing !== before },"Service toggle failed") }},
        {name:"settings-ai-off-collapses-form",run:function() { check(!item("ai.form").visible && !item("ai.key").visible && !item("ai.endpoint").visible,"Disabled AI exposes fields") }},
        {name:"rule-add-reorder-remove",run:function() { var settings=item("settingsView"); var before=settings.routingRules.length; click("rule.add"); check(settings.routingRules.length === before+1,"Rule not added"); var first=settings.routingRules[0].from; click("rule.down.0"); check(settings.routingRules[1].from === first,"Rule not moved"); click("rule.remove."+before); check(settings.routingRules.length === before,"Rule not removed") }},
        {name:"rule-dropdown-and-save",run:function() { choose("rule.to.0","fr"); click("rule.save"); waitFor(function() { return !item("settingsView").saving },"Rules not saved"); check(service.settings.routing.rules[0].to === "fr","Edited rule not persisted") }},
        {name:"failed-rule-save-keeps-draft",run:function() { rpc("tests.mode",{mode:"reject_save"}); choose("rule.to.0","de"); click("rule.save"); waitFor(function() { return !item("settingsView").saving },"Failed save remained busy"); check(item("settingsView").routingRules[0].to === "de" && service.settings.routing.rules[0].to === "fr","Failed save lost draft or changed document"); rpc("tests.mode",{mode:""}); click("rule.save"); waitFor(function() { return !item("settingsView").saving },"Rules save failed") }},
        {name:"ai-key-masking-and-save",run:function() { click("ai.enabled"); check(item("ai.form").visible,"AI form did not open"); edit("ai.model","fixture-model"); edit("ai.key","synthetic-key"); check(item("ai.key").echoMode === TextInput.Password,"Key not masked"); click("ai.save"); waitFor(function() { return !item("settingsView").saving },"AI save stuck"); check(service.settings.ai.model === "fixture-model" && service.settings.ai.has_api_key && item("ai.key").text === "","AI config or key cleanup failed") }},
        {name:"ai-disable-persists-and-preserves-credentials",run:function() { click("ai.enabled"); waitFor(function() { return !item("settingsView").saving },"AI disable stuck"); check(!service.settings.ai.enabled && !item("ai.form").visible && service.settings.ai.has_api_key && service.settings.ai.model === "fixture-model","AI disable lost credentials or did not persist") }},
        {name:"ai-enable-reopens-preserved-form",run:function() { click("ai.enabled"); check(item("ai.form").visible && item("ai.model").text === "fixture-model","AI form lost saved model"); click("ai.save"); waitFor(function() { return !item("settingsView").saving },"AI enable stuck"); check(service.settings.ai.enabled && service.settings.ai.has_api_key,"AI enable failed") }},
        {name:"ai-disable-failure-restores-switch",run:function() { rpc("tests.mode",{mode:"reject_save"}); click("ai.enabled"); waitFor(function() { return !item("settingsView").saving },"Failed AI disable stuck"); check(service.settings.ai.enabled && item("ai.enabled").checked && item("ai.form").visible,"Failed disable hid active AI"); rpc("tests.mode",{mode:""}) }},
        {name:"deepl-test-disabled-without-key",run:function() { click("official.enabled"); check(!item("official.test").enabled,"Connection test enabled without key") }},
        {name:"deepl-unsaved-key-and-connection-test",run:function() { edit("official.key","synthetic-official-key"); check(!item("official.test").enabled,"Unsaved key can be tested"); click("official.save"); waitFor(function() { return !item("settingsView").saving },"Official save stuck"); check(item("official.test").enabled && item("official.key").text === "","Official key state wrong"); click("official.test"); waitFor(function() { return !item("settingsView").saving },"Official test stuck"); check(rpc("tests.state").counts["official.test"] === 1,"Connection test not sent") }},
        {name:"shortcut-edit-save-and-conflict",run:function() { edit("shortcut.input","Super+Q"); click("shortcut.save"); waitFor(function() { return !item("settingsView").saving },"Shortcut save stuck"); check(service.shortcuts.shortcuts.input === "" && !!service.shortcuts.conflicts.input,"Conflict missing") }},
        {name:"shortcut-draft-survives-settings-refresh",run:function() { edit("shortcut.input","Super+Ctrl+Shift+Z"); page("translate"); page("settings"); driver.wait(150); check(item("shortcut.input").text==="Super+Ctrl+Shift+Z","Refresh erased shortcut draft"); click("shortcut.save"); waitFor(function() { return !item("settingsView").saving },"Shortcut save failed") }},
        {name:"ai-model-and-endpoint-drafts-survive-unrelated-save",run:function() { if (!item("ai.enabled").checked) click("ai.enabled"); edit("ai.model","unsaved-model"); edit("ai.endpoint","http://localhost:9999/v1"); click("service.bing"); driver.wait(100); page("translate"); page("settings"); driver.wait(100); check(item("ai.model").text==="unsaved-model" && item("ai.endpoint").text==="http://localhost:9999/v1","Refresh erased AI draft") }},
        {name:"service-drag-immediately-persists-and-orders-results",run:function() { var original=service.serviceOrder.slice(), settings=item("settingsView"); settings.contentY=0; driver.wait(20); dragService("Bing",0); waitFor(function() { return !service.orderSaving },"Order did not persist"); check(service.serviceOrder[0]==="Bing" && rpc("settings").usage.service_order[0]==="Bing","Drag order not saved"); check(!settings.usageDirty,"Drag requires a separate usage save"); check(!find("order.up.0"),"Separate order controls remain"); query("drag order"); check(service.cards[0].service==="Bing" && item("result.Bing").y<item("result.YoudaoDict").y,"Result display ignored service order"); service.translate(service.text,"Bing"); waitFor(function() { return !service.busy },"Retry stuck"); check(service.cards[0].service==="Bing","Retry moved provider to end"); page("settings"); service.reorderServices(original); waitFor(function() { return !service.orderSaving },"Restore order failed") }},
        {name:"service-drag-cancel-and-toggle-do-not-save-order",run:function() { var before=service.serviceOrder.slice(), count=rpc("tests.state").counts["service.order"], handle=item("service.drag.YoudaoDict"); reveal(handle); driver.mousePress(handle,handle.width/2,handle.height/2,Qt.LeftButton,Qt.NoModifier,0); driver.mouseMove(handle,handle.width/2,handle.height*2,12); driver.keyClick(Qt.Key_Escape,Qt.NoModifier,0); driver.mouseRelease(handle,handle.width/2,handle.height/2,Qt.LeftButton,Qt.NoModifier,0); check(JSON.stringify(service.serviceOrder)===JSON.stringify(before) && rpc("tests.state").counts["service.order"]===count,"Cancelled drag saved an order"); click("service.bing"); driver.wait(50); check(JSON.stringify(service.serviceOrder)===JSON.stringify(before),"Toggle changed order"); click("service.bing") }},
        {name:"service-order-save-failure-rolls-back",run:function() { var previous=service.serviceOrder.slice(); rpc("tests.mode",{mode:"reject_save"}); dragService("GoogleFree",0); waitFor(function() { return !service.orderSaving },"Failed order save stuck"); check(JSON.stringify(service.serviceOrder)===JSON.stringify(previous) && JSON.stringify(item("serviceList").order())===JSON.stringify(previous),"Failed save did not roll back"); rpc("tests.mode",{mode:""}) }},
        {name:"rapid-service-drags-preserve-latest-order",run:function() { var original=service.serviceOrder.slice(); rpc("tests.mode",{mode:"slow_order"}); service.reorderServices(["Bing","YoudaoDict","AI","DeepLApi","DeepLFree","GoogleFree"]); service.reorderServices(["GoogleFree","Bing","YoudaoDict","AI","DeepLApi","DeepLFree"]); service.refreshSettings(); waitFor(function() { return !service.orderSaving && !service.wantedOrder },"Queued order saves stuck"); check(service.serviceOrder[0]==="GoogleFree" && rpc("settings").usage.service_order[0]==="GoogleFree","An older reply overwrote the latest order"); rpc("tests.mode",{mode:""}); service.reorderServices(original); waitFor(function() { return !service.orderSaving },"Restore order failed") }},
        {name:"disabled-service-drag-and-keyboard-order-save",run:function() { var original=service.serviceOrder.slice(); click("service.google"); waitFor(function() { return !service.settings.services.google },"Disable failed"); item("settingsView").contentY=0; driver.wait(20); dragService("GoogleFree",0); waitFor(function() { return !service.orderSaving },"Disabled service order did not save"); check(service.serviceOrder[0]==="GoogleFree" && !service.settings.services.google,"Dragging a disabled service enabled it"); click("service.google"); waitFor(function() { return service.settings.services.google },"Enable failed"); check(service.serviceOrder[0]==="GoogleFree","Re-enabling lost position"); var handle=item("service.drag.GoogleFree"); handle.forceActiveFocus(); driver.keyClick(Qt.Key_Down,Qt.NoModifier,0); waitFor(function() { return !service.orderSaving },"Keyboard order did not save"); check(service.serviceOrder[1]==="GoogleFree" && handle.activeFocus,"Keyboard reorder lost position or focus"); service.reorderServices(original); waitFor(function() { return !service.orderSaving },"Restore failed") }},
        {name:"drag-order-keeps-other-unsaved-settings",run:function() { var settings=item("settingsView"), original=service.serviceOrder.slice(), savedDays=service.settings.usage.history_days; settings.changeUsage("history_days",7); settings.contentY=0; driver.wait(20); dragService("Bing",0); waitFor(function() { return !service.orderSaving },"Order save stuck"); check(settings.usageDirty && settings.usageDraft.history_days===7 && service.settings.usage.history_days===savedDays,"Order save overwrote or saved another draft"); settings.usageDirty=false; settings.loadUsage(); service.reorderServices(original); waitFor(function() { return !service.orderSaving },"Restore failed") }},
        {name:"usage-history-policy-save",run:function() { var settings=item("settingsView"), previous=service.serviceOrder.slice(); click("usage.history"); choose("usage.days","30"); choose("usage.limit","1000"); click("usage.save"); waitFor(function() { return !settings.saving },"Usage save stuck"); check(JSON.stringify(service.settings.usage.service_order)===JSON.stringify(previous) && !service.settings.usage.history_enabled && service.settings.usage.history_days===30 && service.settings.usage.history_limit===1000,"Usage policy not saved") }},
        {name:"interface-language-zh-and-en",run:function() { choose("interfaceLanguage","zh-CN"); waitFor(function() { return service.language === "zh-CN" },"Chinese not selected"); check(item("tab.translate").tooltipText === "翻译","Tabs not localized"); choose("interfaceLanguage","en"); waitFor(function() { return service.language === "en" },"English not restored") }},
        {name:"layout-icons-equal-and-language-between-input-results",run:function() { page("translate"); var input=item("translationInput"); var language=item("sourceLanguage"); var result=item("result.Bing"); check(input.mapToItem(panel,0,input.height).y <= language.mapToItem(panel,0,0).y,"Language selector is above input"); var icons=["tab.translate","tab.history","tab.favorites","tab.settings","panelClose"].map(item); check(icons.every(function(icon) { return icon.width===icons[0].width && icon.height===icons[0].height }),"Icon buttons have inconsistent sizing") }},
        {name:"system-editor-handled-without-native-panel-or-translation",run:function() { var before=rpc("tests.state").counts.translate; var id=service.request("capture",{action:"annotate"}); check(service.pending[id].deadline===0,"Interactive editor has a forced deadline"); service.expire(); check(!!service.pending[id],"User-paced editor expired"); waitFor(function() { return !service.pending[id] },"System editor result missing"); check(controller.page==="translate" && rpc("tests.state").counts.translate===before,"Editor opened native annotation or translated") }},
        {name:"capture-cancel-preserves-input",run:function() { page("translate"); service.text="retained"; rpc("tests.mode",{mode:"cancel_capture"}); service.capture("screenshot"); waitFor(function() { return !service.captureBusy },"Capture stayed busy"); check(service.text === "retained","Cancelled capture changed text"); rpc("tests.mode",{mode:""}) }},
        {name:"silent-ocr-does-not-translate",run:function() { var before=rpc("tests.state").counts.translate; service.capture("ocr"); waitFor(function() { return !service.captureBusy },"OCR stayed busy"); check(rpc("tests.state").counts.translate === before && service.notice === service.tr("copied"),"OCR invoked translation") }},
        {name:"capture-translates-recognized-text",run:function() { service.capture("selection"); waitFor(function() { return !service.captureBusy && !service.busy && service.text === "captured fixture" },"Selection capture failed") }},
        {name:"stale-selection-cannot-refill-a-new-input",run:function() { var before=rpc("tests.state").counts.translate; service.capture("selection"); service.clear(); service.text="new input"; waitFor(function() { return Object.keys(service.pending).length===0 },"Old selection did not finish"); check(service.text==="new input" && service.cards.length===0 && !service.busy && !service.captureBusy,"Old selection refilled new input"); check(rpc("tests.state").counts.translate===before,"Old selection translated after Clear") }},
        {name:"empty-selection-clears-old-query-without-translating",run:function() { var before=rpc("tests.state").counts.translate; controller.opened=false; controller.page="history"; rpc("tests.mode",{mode:"empty_selection"}); service.capture("selection"); waitFor(function() { return !service.captureBusy },"Empty selection stayed busy"); check(service.text==="" && service.cards.length===0 && !service.busy && service.error==="" && service.notice==="","Empty selection kept old contents"); check(controller.opened && controller.page==="translate","Empty selection did not open the input panel"); driver.wait(20); check(item("translationInput").activeFocus,"Empty selection did not focus the input"); check(rpc("tests.state").counts.translate===before,"Empty selection submitted a translation"); rpc("tests.mode",{mode:""}) }},
        {name:"escape-cancels-request-and-preserves-input",run:function() { controller.opened=true; page("translate"); edit("translationInput","slow fixture"); click("translateSubmit"); item("translationInput").forceActiveFocus(); driver.keyClick(Qt.Key_Escape,Qt.NoModifier,0); check(!controller.opened && !service.busy && service.text === "slow fixture","Escape semantics changed"); controller.opened=true; driver.wait(200); check(service.cards.every(function(card) { return !card.pending }),"Stale response restored pending cards") }},
        {name:"cooldown-localization-and-settings-recovery",run:function() { service.cards=[{service:"Bing",text:"hello",paragraphs:[],error:"限流",failure:{code:"rate_limited",retry_at_ms:Date.now()+60000}}]; driver.wait(30); check(!item("retry.Bing").enabled && /s$/.test(item("retry.Bing").text),"Cooldown is clickable or has no countdown"); service.now=Date.now()+61000; check(item("retry.Bing").enabled,"Retry did not unlock"); service.cards=[{service:"Bing",text:"hello",paragraphs:[],error:"配置",failure:{code:"configuration"}}]; driver.wait(30); click("retry.Bing"); check(controller.page==="settings","Configuration recovery does not open settings"); page("translate") }},
        {name:"partial-stream-visible-and-isolated",run:function() { service.requestId="stream-probe"; service.busy=true; service.cards=Model.start([], ["AI"],""); service.accept(JSON.stringify({event:"translation",data:{request_id:"stream-probe",kind:"delta",data:{service:"AI",text:"partial translation"}}})); driver.wait(30); check(item("resultText.AI").visible && service.cards[0].pending,"Partial translation hidden"); service.accept(JSON.stringify({event:"translation",data:{request_id:"old-stream",kind:"delta",data:{service:"AI",text:"stale"}}})); check(service.cards[0].paragraphs[0]==="partial translation","Stale partial replaced text"); service.stop(); check(service.cards[0].partial && !service.cards[0].pending,"Cancelled stream lost partial state") }},
        {name:"malformed-favorite-and-failure-replies-are-rejected",run:function() { check(!service.validReply("favorite.toggle",{id:"bad"}),"Invalid favorite state accepted"); check(!service.validFailure({code:"rate_limited",retry_at_ms:"tomorrow"}),"Invalid cooldown accepted"); check(!service.validReply("history.list",[{id:1,text:"t",result:"r",service:"AI",details:[{service:"AI",paragraphs:"bad"}]}]),"Invalid history details accepted") }},
        {name:"keyboard-result-copy-and-focus",run:function() { query("keyboard shortcuts"); item("translationInput").forceActiveFocus(); driver.keyClick(Qt.Key_L,Qt.ControlModifier,0); check(item("translationInput").selectedText==="keyboard shortcuts","Ctrl+L did not select input"); driver.keyClick(Qt.Key_Down,Qt.ControlModifier,0); check(panel.activeResult===1,"Result navigation failed"); driver.keyClick(Qt.Key_C,Qt.ControlModifier|Qt.ShiftModifier,0); waitFor(function() { return service.notice===service.tr("copied") },"Result copy shortcut failed"); check(rpc("tests.state").last.copy.text==="translated: keyboard shortcuts","Keyboard copied wrong translation") }},
        {name:"theme-switch-keeps-input-and-results",run:function() { query("theme fixture"); var input=service.text; var cards=JSON.stringify(service.cards); Color.loadColors('foreground = "#eeeedd"\nbackground = "#151515"\naccent = "#cc6644"'); Color.loadShell('[font]\nbase-size = 15'); driver.wait(30); check(service.text === input && JSON.stringify(service.cards) === cards,"Theme lost state"); check(item("translationInput").font.pixelSize === Style.font.body,"Input font not synchronized") }},
        {name:"theme-secondary-text-contrast",run:function() {
            [
                {muted:"#2d3450",text:"#ddf7ff",background:"#0b0c16"},
                {muted:"#e4e4e4",text:"#222222",background:"#fafafa"},
                {muted:"#777777",text:"#eeeeee",background:"#111111"}
            ].forEach(function(palette) {
                var muted=Qt.color(palette.muted), text=Qt.color(palette.text), background=Qt.color(palette.background)
                var result=Theme.secondary(muted,text,background)
                check(Theme.contrast(result,background)>=4.5-0.001,"Theme text remains unreadable")
                if(Theme.contrast(muted,background)>=4.5) check(result.toString()===muted.toString(),"Readable theme muted color was replaced")
            })
        }},
        {name:"compact-panel-height-follows-content",run:function() { var cards=service.cards; service.cards=[]; service.busy=false; check(panel.preferredHeight===Style.space(300),"Empty panel is not compact"); service.cards=cards; check(panel.preferredHeight===Style.space(600),"Results do not expand the panel"); controller.page="settings"; check(panel.preferredHeight===Style.space(620),"Settings height wrong"); controller.page="translate" }},
        {name:"resize-keeps-visible-header-and-input",run:function() { panel.width=440; panel.height=650; driver.wait(30); var input=item("translationInput"); check(input.width > 0 && input.width < panel.width,"Input layout broke"); panel.width=580; panel.height=770 }},
        {name:"protocol-invalid-json-and-null",run:function() { ["{broken","null","[]","42"].forEach(function(value) { service.accept(value) }); check(service.ready,"Invalid frame disconnected valid backend") }},
        {name:"protocol-malformed-stream-payloads",run:function() { service.requestId="schema"; service.busy=true; [null,{}, {request_id:"schema",kind:"start",data:null}, {request_id:"schema",kind:"start",data:{services:null}}, {request_id:"schema",kind:"result",data:null}, {request_id:"schema",kind:"warning",data:null}].forEach(function(value) { service.accept(JSON.stringify({event:"translation",data:value})) }); service.stop(); check(service.ready,"Malformed event disconnected backend") }},
        {name:"protocol-wrong-version-rejected",run:function() { var isolated=Qt.createQmlObject('import QtQuick; import "Native" as Native; Native.Service { autostart:false }',root); isolated.accept('{"event":"ready","data":{"protocol":99}}'); check(!isolated.ready,"Unsupported protocol accepted"); isolated.destroy() }},
        {name:"protocol-unknown-provider-and-invalid-result",run:function() { service.requestId="schema"; service.busy=true; service.accept(JSON.stringify({event:"translation",data:{request_id:"schema",kind:"start",data:{services:["Bing"]}}})); service.accept(JSON.stringify({event:"translation",data:{request_id:"schema",kind:"result",data:{service:"Unexpected",paragraphs:["unexpected"]}}})); service.accept(JSON.stringify({event:"translation",data:{request_id:"schema",kind:"result",data:{service:"Bing",paragraphs:{bad:true}}}})); check(service.cards.length===1 && service.cards[0].pending,"Invalid provider result rendered"); service.stop() }},
        {name:"protocol-malformed-reply-finalizes-with-error",run:function() { var failed=false; var id=service.request("tests.ignore",{},function(ok) { failed=!ok }); service.accept(JSON.stringify({id:id,ok:true,data:null})); check(failed && !service.pending[id],"Malformed reply left callback or reported success") }},
        {name:"protocol-malformed-settings-keeps-valid-document",run:function() { var document=JSON.stringify(service.settings); var id=service.request("settings",{}); service.accept(JSON.stringify({id:id,ok:true,data:{preferences:{language:"en"},services:{},ai:{},official:{},routing:{rules:null}}})); check(JSON.stringify(service.settings)===document,"Malformed settings replaced document") }},
        {name:"late-translation-rejection-does-not-cancel-new-request",run:function() { service.translate("hang fixture"); var old=service.requestId; service.translate("hang fixture"); var current=service.requestId; service.accept(JSON.stringify({id:old,ok:false,error:"late fixture failure"})); check(service.busy && service.requestId===current && !service.error,"Late rejection stopped replacement or showed stale error"); service.stop(); driver.wait(50) }},
        {name:"request-timeout-releases-busy-ui",run:function() { var before=service.commandTimeoutMs; service.commandTimeoutMs=60; var failed=false; service.request("tests.ignore",{},function(ok) { failed=!ok }); waitFor(function() { return failed },"Unanswered request never timed out"); check(Object.keys(service.pending).length===0,"Timed out request retained"); service.commandTimeoutMs=before }},
        {name:"request-backpressure-is-bounded",run:function() { var failed=0; for(var i=0;i<80;i++) service.request("tests.ignore",{},function(ok) { if(!ok) failed++ }); check(Object.keys(service.pending).length<=64 && failed>=16,"Pending map unbounded"); var ids=Object.keys(service.pending); ids.forEach(function(id) { service.accept(JSON.stringify({id:id,ok:false,error:"fixture release"})) }); check(Object.keys(service.pending).length===0,"Pending map not released") }},
        {name:"translation-stream-timeout-finalizes-cards",run:function() { var previous=service.streamTimeoutMs; service.streamTimeoutMs=60; service.translate("hang fixture"); waitFor(function() { return !service.busy },"Missing stream completion never timed out"); check(service.cards.length===2 && service.cards.every(function(card) { return !card.pending && !!card.error }),"Timeout left cards pending"); service.streamTimeoutMs=previous }},
        {name:"stress-500-theme-and-font-changes",run:function() { query("theme fixture"); var input=service.text; var cards=JSON.stringify(service.cards); for(var i=0;i<500;i++) { Color.loadColors(i%2 ? 'foreground = "#eeeeee"\nbackground = "#151515"\naccent = "#cc6644"' : 'foreground = "#111111"\nbackground = "#ffffff"\naccent = "#2277cc"'); if(i%10===0) { Color.loadShell('[font]\nbase-size = '+(12+i%6)); driver.wait(1) } }; check(service.text===input && JSON.stringify(service.cards)===cards,"Theme stress lost state"); Color.loadShell('[font]\nbase-size = 15') }},
        {name:"stress-2000-stale-events-do-not-render",run:function() { var cards=JSON.stringify(service.cards); for(var i=0;i<2000;i++) service.accept(JSON.stringify({event:"translation",data:{request_id:"stale"+i,kind:"result",data:{service:"Bing",paragraphs:["stale"]}}})); check(JSON.stringify(service.cards)===cards,"Stale flood altered results") }},
        {name:"stress-80-page-switches-and-resizes",run:function() { for(var i=0;i<80;i++) { controller.page=["translate","history","favorites","settings"][i%4]; panel.width=440+i%3*40; panel.height=650+i%3*40; if(i%4===0) driver.wait(5) }; controller.page="translate"; panel.width=580; panel.height=770; driver.wait(100); check(service.text==="theme fixture","Tab stress lost input"); check(Object.keys(service.pending).length===0,"Tab stress left pending callbacks") }},
        {name:"stress-100-panel-create-destroy",run:function() { var component=Qt.createComponent("Native/PanelContent.qml"); check(component.status===Component.Ready,"Panel component unavailable"); for(var i=0;i<100;i++) { var instance=component.createObject(window,{controller:controller,width:580,height:770,visible:false}); check(!!instance,"Panel creation failed"); instance.destroy(); driver.wait(1) }; check(service.text==="theme fixture","Panel recreation lost service state") }},
        {name:"backend-crash-clears-pending-state",run:function() { var failed=false; service.request("tests.ignore",{},function(ok) { failed=!ok }); service.autostart=false; service.request("tests.crash",{}); waitFor(function() { return !service.ready && failed },"Backend death left callbacks pending"); check(Object.keys(service.pending).length === 0 && !service.busy,"Backend death left pending state"); controller.page="translate" }},
        {name:"manual-backend-reconnect",run:function() { service.reconnect(); waitFor(function() { return service.ready && service.settings.preferences.language === "en" },"Reconnect failed"); check(service.text === "theme fixture","Reconnect lost input") }},
        {name:"startup-failure-retries-are-bounded",run:function() { service.autostart=false; service.backend.running=false; waitFor(function() { return !service.ready },"Fixture did not stop"); service.backend.command=["python3","-c","raise SystemExit(9)"]; service.failures=0; service.autostart=true; service.backend.running=true; waitFor(function() { return service.failures===4 && !service.backend.running },"Startup retries were not bounded",17000); service.autostart=false; driver.wait(200); check(service.failures===4 && Object.keys(service.pending).length===0,"Startup failure retained work") }},
        {name:"reconnect-after-retry-limit-recovers",run:function() { service.backend.command=["python3",Quickshell.env("NATIVE_UI_BACKEND_FIXTURE")]; service.reconnect(); waitFor(function() { return service.ready && service.failures===0 },"Recovery after retry limit failed"); check(service.text==="theme fixture","Repeated failure lost input") }}
    ]
    function next() {
        if (index === cases.length) {
            console.log("NATIVE_UI_PASS cases=" + index)
            service.autostart=false; service.backend.running=false; Qt.quit(); return
        }
        var test=cases[index]
        try { test.run(); console.log("NATIVE_UI_CASE_PASS " + test.name); index++; step.restart() }
        catch (error) { console.error("NATIVE_UI_FAIL " + test.name + ": " + error); Qt.exit(1) }
    }
    Component.onCompleted: {
        service.shell=shellApi
        service.backend.command=["python3",Quickshell.env("NATIVE_UI_BACKEND_FIXTURE")]
        service.autostart=true
    }
    Timer { running:true; interval:350; onTriggered: { root.window.requestActivate(); root.waitFor(function() { return root.service.ready },"Backend did not start"); root.next() } }
    Timer { id:step; interval:20; onTriggered:root.next() }
}
